### ISSUE TITLE
release docker merge from develop to master is not working

### ISSUE THREAD

**Issue by stevehu** [networknt/light-bot#29]
As the checkout is on the master branch, the develop branch is not checked yet. The two options for us:

* Remove the merge step as release maven task has merged everything
* Checkout develop branch explicitly before merging

https://stackoverflow.com/questions/3999541/after-git-clone-i-do-not-see-my-branch?lq=1

**Comment by ddobrin** [comment]
Checking the develop branch out is simple and would allow also a diff, if somebody wishes to do that. Then, do the merging.

**Comment by stevehu** [comment]
I agree that would be the easiest way to do. Also, depending on release maven to merge from the develop branch to the master branch is not reliable.

**Comment by stevehu** [comment]
Just like the release-maven task, check out to the develop branch first will resolve the problem. I have made the change to config files in light-config-test/light-bot/release-docker/
