### ISSUE TITLE
Is there now a preference for gradle?

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-bot#5]
Hi @stevehu 

Noticed this was written using gradle and was just wondering why the sudden move from maven?
Since the entire ecosystem was built using maven, just seemed like a interesting choice (I'm a huge fan 😃 )

Thanks!

**Comment by stevehu** [comment]
There are still a lot of things that need to be figured out for example deploy to Maven central, code coverage etc.

**Comment by NicholasAzar** [comment]
That's great to hear! There is good integration between gradle and maven (like packaging artifacts into .m2) so a migration if/when it comes up could be done incrementally without much disruption.
Are there any examples that are built with gradle right now?

**Comment by stevehu** [comment]
There is no examples yet except the light-bot itself. I am thinking about updating one of the petstore  example to test the water. Once it is done, we can put it into the light-codegen to give end user two options.

**Comment by NicholasAzar** [comment]
I'm interested to take a look into this as well. Thanks for your time!
