### ISSUE TITLE
add gradle support for build along with maven

### ISSUE THREAD

**Issue by stevehu** [networknt/light-bot#55]
It would be great for the bot to detect the build framework before calling the command. Or call maven first and then gradle?

**Comment by ddobrin** [comment]
We'll check whether a certain directory, where a Git repo has been cloned, has either a:
-- pom.xml
-- build.gradle.kts 
file.

Must be tried first but this should do it

**Comment by ddobrin** [comment]
If people have both in the same folder, we can say: Gradle first, Maven second.
Even allow a choice if that's the case
