### ISSUE TITLE
package name in test/ of almost all sub-projects are incorrect

### ISSUE THREAD

**Issue by lanphan** [networknt/light-bot#60]
I see that package name in test/ of all sub-projects below:
1/ exec-core
2/ exec-develop-build
3/ exec-regex-replace
4/ exec-release-maven
5/ exec-version-upgrade

are not correct: they're just 1 folder with name like "com.networknt....", not a hierarchical levels of folders ... Importing them into Eclipse raised errors a lot (only package name in test/ of exec-release-docker is correct)

However, running `./gradlew build` does not raise any error, still don't know why ...

**Comment by ddobrin** [comment]
As there is a single folder with code in exec-develop-build, for example, 
Eclipse shows it as such: com.networknt.bot.develop

Looking at the file system, you can notice that the code is in a hierarchy of folders:
...
~/work/bot/light-bot/exec-develop-build/src/main/java/com/networknt/bot/develop:>ls -lart
total 56
drwxr-xr-x  3 ...  staff    102 20 Apr  2018 ..
-rw-r--r--  1 ...  staff  19035 14 Feb 09:58 DevelopBuildTask.java
-rw-r--r--  1 ...  staff   5031 14 Feb 09:58 ConfigUtils.java
drwxr-xr-x  4 ...  staff    136 14 Feb 09:58 .
...

**Comment by ddobrin** [comment]
@lanphan : the issue has been addressed in the develop branch; please update your branch

It will be released over the week-end to master by @stevehu

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [package name in test/ of almost all sub-projects are incorrect](https://trello.com/c/LwHiGbjo/89-package-name-in-test-of-almost-all-sub-projects-are-incorrect)
