### ISSUE TITLE
Recipient email should be read from configuration file

### ISSUE THREAD

**Issue by DineshAlapati** [networknt/light-bot#7]
Currently, recipient email is hardcoded within main class. This property should be read from configuration file (email.yml)

**Comment by stevehu** [comment]
@DineshAlapati You are right. It is a good idea to put into config file. Will make the change once I have a chance.

**Comment by ddobrin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Light-bot: Recipient email should be read from configuration file](https://trello.com/c/VPh5pITR/9-light-bot-recipient-email-should-be-read-from-configuration-file)
