### ISSUE TITLE
Allow the skipping of tests on an individual repo basis

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-bot#79]
At this time, tests can be skipped for all repos:
...skip_test: false

It is desired to be able to add a named task and be able to disable testing for individual repos, for example:
  buildProjectsNoTest:
    skip: false
    skip_test: true
    project:
      - api-project-x

The change must be transparent for existing users of the develop-build task

**Comment by stevehu** [comment]
@ddobrin Could you please update the document as well at https://github.com/networknt/light-doc/blob/master/content/en/tool/light-bot/task/develop-build.md?

**Comment by ddobrin** [comment]
will do
