### ISSUE TITLE
need to find a why to make develop-build take -Prelease profile

### ISSUE THREAD

**Issue by stevehu** [networknt/light-bot#95]
for the light-example-4j build as they are all applications.

**Comment by ddobrin** [comment]
I think that has already been addressed (unless I am mistaken(:
DevelopBuildTask.java:
```
...
				if(buildFatJar)
					mavenCmd += " -Prelease";
...
```

**Comment by stevehu** [comment]
The problem is that the build config I have contains both light-4j frameworks and light-example-4j together. If I use buildFatJar flag, the light-4j will be build with -Prelease and a warning message is displayed. I guess it is OK anyway. Let me try it out and see if the test cases can be executed successfully. Thanks.

```
The requested profile "release" could not be activated because it does not exist.
```

**Comment by stevehu** [comment]
@ddobrin I had an issue in my config file previously. After fixing the issue, the buildFatJar working. Thanks.
